version: '3.7'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8081:8080"
    volumes:
      - ./docs/openapi.yaml:/data/openapi.yaml
    environment:
      SWAGGER_JSON: /data/openapi.yaml